### ISSUE TITLE
Fatal error: Unexpected end of input

### ISSUE THREAD

**Issue by chapati23** [andyshora/grunt-yslow#5]
doesn't work for me. if i start grunt yslow i always get:

```
Running "yslow:pages" (yslow) task
>> Testing 1 URLs, this might take a few moments...
Fatal error: Unexpected end of input
```

this is my config (in coffeescript)

```
    yslow:
      options:
        thresholds:
          weight: 180
          speed: 1000
          score: 80
          requests: 15
      pages:
        files: [
          { src: 'http://google.com' }
        ]
```
